#######################
# Theme Customization #
#######################

title: 学习报告                            # used in <title> tag & site header
author: Wxd Yin                        # used in a <meta> tag & /feed.xml
description: >                              # used in a <meta> tag & /feed.xml
  It's really a hard work for me ! !
slogan: W x d                           # used in site header, beside title
avatar: /i/avatar.png                       # 主页标题头像
banner: /i/mountains.svg                    # 主页标题背景
url: http://solana.ryanlue.com              # used by plugins to generate feed.xml and sitemap.xml
baseurl: '/929384921.github.io'                                 # prepended to all absolute filepaths
repo: https://github.com/rlue/jekyll-solana # used in footer

# Objects listed here will appear in the main nav menu.
# Exceeding four items may cause problems on the desktop (>900px wide) layout.
nav_menu:
  - name: 学习笔记
    url: /
    icon: /i/icons.svg#posts # 图标 像素should be 24x24 px.
  - name: 作品集
    url: /
    icon: /i/icons.svg#portfolio # 图标
  - name: GitHub
    url: https://github.com/Yin926/
    icon: /i/icons.svg#github
    outbound: true      # this key sets a link to open in a new window.
  - name: 联系我
    scheme: mailto      # these keys enable email obfuscation.
    handle: hello       # you know, to protect you from bots. (handle and domain
    domain: github.com  # are separated in case bots crawl GitHub repos, too.)
    icon: /i/icons.svg#email

# Objects listed here will appear on the /projects.html page.
作品集:
  - title: Solana
    teaser: A responsive blog template written in Sass and vanilla JavaScript.
    url: https://github.com/rlue/jekyll-solana
    role: Creator
    category: Frontend Dev
  - title: Cortana
    teaser: A talking robot. Now available on Google Play?
    url: https://play.google.com/store/apps/details?id=com.microsoft.cortana
    role: Core Team
    category: NLP
  - title: Rihanna
    teaser: Possibly another robot. Also available on Google Play.
    url: https://play.google.com/store/music/artist/Rihanna?id=Arcw2m2ih45qntv3fufub25tyhu
    role: Contributor
    category: Algorithmic Composition

#################
# Site Settings #
#################

incremental: true
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - TODO.md

permalink: /:collection/:path

collections:
  category: { output: true }
  tag:      { output: true }

defaults:
  - scope:  { type:   posts    }
    values: { layout: post     }
  - scope:  { type:   tag      }
    values: { layout: listing  }
  - scope:  { type:   category }
    values: { layout: listing  }

sass:
  sass_dir: _assets/css

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

paginate: 10
